version: "3.9"
services:
  api:
    build: ./api
    environment:
      - MONGO_URL=
    ports:
      - 8000:8000
  cdn:
    build: ./cdn
    ports:
      - 8080:8080
  web:
    build: ./web
    ports:
      - 3000:3000
